export const AdvisorData = [
    {
        "Name": "KAVITHA MENON",
        "Registration_no": "INA000000037",
        "contact_person": "KAVITHA MENON",
        "Address": "015, Workafella, 12, AK EState, Off Veer Savarkar Flyover, Besides Radisson Blu Hotel, SV Road, Goregaon West",
        "Email": "cavithamenon@gmail.com",
        "Telephone": "919821455882",
        "City": "MUMBAI",
        "State": "MAHARASHTRA",
        "pincode": "400062",
        "category": "RIA",
        "Book Slot":"Book"
    },
    {
        "Name": "PRAKASH CHANDRA PRAHARAJ",
        "Registration_no": "INA000000045",
        "contact_person": "Prakash Chandra Praharaj",
            "Address": "36/5, 3rd Floor, Hustlehub Tech Park, Sector 2, HSR Layout",
            "Email": "Prakash.praharaj@gmail.com",
            "Telephone": "2227575648",
            "fax": "2227575648",
            "City": "BANGALORE",
            "State": "KARNATAKA",
            "pincode": "560102",
        "category": "RIA",
        "Book Slot":"Book"
    },
    {
        "Name": "VALUEFY SOLUTIONS PRIVATE LIMITED",
        "Registration_no": "INA000000060",
        "contact_person": "Mr. Sumeet Kumar Agrawal",
        
            "Address": "D-401, Tulip Valley of Flowers, Thakur Village, Kandivali East",
            "Email": "sumeet@valuefy.com",
            "Telephone": "022 32264400",
            "fax": "022 32264400",
            "City": "MUMBAI",
            "State": "MAHARASHTRA",
            "pincode": "400101",
        "category": "RIA",
        "Book Slot":"Book"
    },
    {
        "Name": "PANKAJ UDAYKUMAR KULKARNI",
        "Registration_no": "INA000000078",
        "contact_person": "Pankaj UdayKumar Kulkarni",
        
            "Address": "36/5, 3rd Floor, Hustlehub Tech Park, Sector 2, HSR Layout",
            "Email": "ia.pankaj.kulkarni@gmail.com",
            "Telephone": "02024221405",
            "fax": "02024221405",
            "City": "BANGALORE",
            "State": "KARNATAKA",
            "pincode": "560102",
        "category": "RIA",
        "Book Slot":"Book"
    },
    {
        "Name": "ICICI SECURITIES LIMITED",
        "Registration_no": "INA000000094",
        "contact_person": "Abhishake Mathur Senior Vice President",
            "Address": "ICICI VENTURE HOUSE, APPASAHEB MARATHE MARG, PRABHADEVI",
            "Email": "abhishake.mathur@icicisecurities.com",
            "Telephone": "2240701382",
            "fax": "2240701382",
            "City": "MUMBAI",
            "State": "MAHARASHTRA",
            "pincode": "400025",
        "category": "RIA",
        "Book Slot":"Book"
    },
    {
        "Name": "STAKEHOLDERS EMPOWERMENT SERVICES",
        "Registration_no": "INH000000016",
        "contact_person": "MR. DEVENDRA BHANDARI",
            "Address": "A202, MUKTANGAN COMPLEX, UPPER GOVIND NAGAR, MALAD (EAST)",
            "Email": "devendra.bhandari@sesgovernance.com",
            "Telephone": "2240220322",
            "fax": "2240220322",
            "City": "MUMBAI",
            "State": "MAHARASHTRA",
            "pincode": "400097",
        "category": "RA",
        "Book Slot":"Book"
    },
    {
        "Name": "INSTITUTIONAL INVESTOR ADVISORY SERVICES INDIA LIMITED",
        "Registration_no": "INH000000024",
        "contact_person": "AMIT TANDON",
            "Address": "GROUND FLOOR, DGP HOUSE, 88-C, OLD PRABHADEVI ROAD",
            "Email": "amit.tandon@iias.in",
            "Telephone": "2222721575",
            "fax": "2222721575",
            "City": "MUMBAI",
            "State": "MAHARASHTRA",
            "pincode": "400025",
        "category": "RA",
        "Book Slot":"Book"
    },
    {
        "Name": "DEEPAK KUMAR KANODIA",
        "Registration_no": "INH000000032",
        "contact_person": "DEEPAK KUMAR KANODIA",
            "Address": "36/5, 3rd Floor, Hustlehub Tech Park, Sector 2, HSR Layout",
            "Email": "deepakkrkanodia@gmail.com",
            "Telephone": "02228392567",
            "fax": "02228392567",
            "City": "BANGALORE",
            "State": "KARNATAKA",
            "pincode": "560102",
        "category": "RA",
        "Book Slot":"Book"
    },
    {
        "Name": "BOB CAPITAL MARKETS LIMITED",
        "Registration_no": "INH000000040",
        "contact_person": "MR. GOLAK B PANDA",
            "Email": "golak.panda@bobcaps.in",
            "Telephone": "2266718535",
            "fax": "2266718535",
            "Address": "36/5, 3rd Floor, Hustlehub Tech Park, Sector 2, HSR Layout",
            "City": "BANGALORE",
            "State": "KARNATAKA",
            "pincode": "560102",
        "category": "RA",
        "Book Slot":"Book"
    },
    {
        "Name": "Chavod Dasharathbhai Narsangabhai",
        "Registration_no": "INA000019354",
        "Contact_Person": "Dasharathbhai Chavod",
            "Address": "5th Floor, Office No 12, Vihav Supremus, Near Amin Party Plot",
            "City": "VADODARA",
            "State": "GUJARAT",
            "Pincode": "391101",
        "Email": "DASARTHSINGH@GMAIL.COM",
        "Telephone": "919725391258",
        "Fax": null,
        "Registration_Date": "Jul 02, 2024",
        "License_Type": "Perpetual",
        "category":"MFD",
        "Book Slot":"Book"
    },
    {
        "Name": "Mahesh Thangaraju - Proprietor EquityStreet Investment Advisor",
        "Registration_no": "INA000019363",
        "Contact_Person": "Mahesh Thangaraju",
            "Address": "504, Brigade Exotica Apartment, Old Madras Road, Before Budigere Cross, Avalahalli, Virgonagar",
            "City": "BANGALORE",
            "State": "KARNATAKA",
            "Pincode": "560049",
        "Email": "naresh.pandya@bseasl.com",
        "Telephone": null,
        "Fax": null,
        "Registration_Date": "Jul 02, 2024",
        "License_Type": "Perpetual",
        "category":"MFD",
        "Book Slot":"Book"
    },
    {
        "Name": "Credit Suisse Securities India Private Limited",
        "Registration_no": "INA000019372",
        "Contact_Person": "Pravin Kurundwad",
            "Address": "9th Floor, Ceejay House, Plot F, Shivsagar EState, Dr Annie Besant Road, Worli",
            "City": "MUMBAI",
            "State": "MAHARASHTRA",
            "Pincode": "400018",
        "Email": "pravin.kurundwad@credit-suisse.com",
        "Telephone": "912267773599",
        "Fax": "912267773599",
        "Registration_Date": "Jul 04, 2024",
        "License_Type": "Perpetual",
        "category":"MFD",
        "Book Slot":"Book"
    },
    {
        "Name": "Sanket Awate Fintech Private Limited",
        "Registration_no": "INA000019381",
        "Contact_Person": "Sanket Awate",
            "Address": "1786/A, Ameya Empire, Fl. No. Tf-4, 1st Lane, Rajarampuri",
            "City": "KOLHAPUR",
            "State": "MAHARASHTRA",
            "Pincode": "416008",
        "Email": "sanketawate111@gmail.com",
        "Telephone": "91007385107220",
        "Fax": "91007385107220",
        "Registration_Date": "Jul 15, 2024",
        "License_Type": "Perpetual",
        "category":"MFD",
        "Book Slot":"Book"
    },
    {
        "Name": "Seshaphani Jonnalagadda Proprietor of Invest Street Investment Advisers",
        "Registration_no": "INA000019390",
        "Contact_Person": "Seshaphani Jonnalagadda",
            "Address": "36/5, 3rd Floor, Hustlehub Tech Park, Sector 2, HSR Layout",
            "City": "BANGALORE",
            "State": "KARNATAKA",
            "Pincode": "560102",
        "Email": "phani.seshu@gmail.com",
        "Telephone": "918879752365",
        "Fax": null,
        "Registration_Date": "Jul 18, 2024",
        "License_Type": "Perpetual",
        "category":"MFD",
        "Book Slot":"Book"
    },
    {
        "Name": "N Prabhanjan Rao Proprietor Elysian Investment Advisory Services",
        "Registration_no": "INA000019406",
        "Contact_Person": "N Prabhanjan Rao",
            "Address": "7, Sridevi Complex, NAT Street, Basavanagudi",
            "City": "BANGALORE",
            "State": "KARNATAKA",
            "Pincode": "560004",
        "Email": "rao@cfooptimus.com",
        "Telephone": "917760796280",
        "Fax": null,
        "Registration_Date": "Jul 18, 2024",
        "License_Type": "Perpetual",
        "category":"MFD",
        "Book Slot":"Book"
    },
    {
        "Name": "Chavod Dasharathbhai Narsangabhai",
        "Registration_no": "INA000019354",
        "contact_person": "Dasharathbhai Chavod",
            "Address": "5th Floor, Office No 12, Vihav Supremus, Near Amin Party Plot",
            "City": "VADODARA",
            "State": "GUJARAT",
            "pincode": "391101",
        "Email": "DASARTHSINGH@GMAIL.COM",
        "Telephone": "919725391258",
        "fax": null,
        "registration_date": "Jul 02, 2024",
        "license_type": "Perpetual",
        "category": "MFD",
        "Book Slot":"Book"
    },
    {
        "Name": "Mahesh Thangaraju - Proprietor EquityStreet Investment Advisor",
        "Registration_no": "INA000019363",
        "contact_person": "Mahesh Thangaraju",
            "Address": "504, Brigade Exotica Apartment, Old Madras Road, Before Budigere Cross, Avalahalli, Virgonagar",
            "City": "BANGALORE",
            "State": "KARNATAKA",
            "pincode": "560049",
        "Email": "naresh.pandya@bseasl.com",
        "Telephone": null,
        "fax": null,
        "registration_date": "Jul 02, 2024",
        "license_type": "Perpetual",
        "category": "MFD",
        "Book Slot":"Book"
    },
    {
        "Name": "Credit Suisse Securities India Private Limited",
        "Registration_no": "INA000019372",
        "contact_person": "Pravin Kurundwad",
            "Address": "9th Floor, Ceejay House, Plot F, Shivsagar EState, Dr Annie Besant Road, Worli",
            "City": "MUMBAI",
            "State": "MAHARASHTRA",
            "pincode": "400018",
        "Email": "pravin.kurundwad@credit-suisse.com",
        "Telephone": "912267773599",
        "fax": "912267773599",
        "registration_date": "Jul 04, 2024",
        "license_type": "Perpetual",
        "category": "MFD",
        "Book Slot":"Book"
    },
    {
        "Name": "Sanket Awate Fintech Private Limited",
        "Registration_no": "INA000019381",
        "contact_person": "Sanket Awate",
            "Address": "1786/A, Ameya Empire, Fl. No. Tf-4, 1st Lane, Rajarampuri",
            "City": "KOLHAPUR",
            "State": "MAHARASHTRA",
            "pincode": "416008",
        "Email": "sanketawate111@gmail.com",
        "Telephone": "91007385107220",
        "fax": "91007385107220",
        "registration_date": "Jul 15, 2024",
        "license_type": "Perpetual",
        "category": "MFD",
        "Book Slot":"Book"
    },
    {
        "Name": "Seshaphani Jonnalagadda Proprietor of Invest Street Investment Advisers",
        "Registration_no": "INA000019390",
        "contact_person": "Seshaphani Jonnalagadda",
            "Address": "36/5, 3rd Floor, Hustlehub Tech Park, Sector 2, HSR Layout",
            "City": "BANGALORE",
            "State": "KARNATAKA",
            "pincode": "560102",
        "Email": "phani.seshu@gmail.com",
        "Telephone": "918879752365",
        "fax": null,
        "registration_date": "Jul 18, 2024",
        "license_type": "Perpetual",
        "category": "MFD",
        "Book Slot":"Book"
    },
    {
        "Name": "N Prabhanjan Rao Proprietor Elysian Investment Advisory Services",
        "Registration_no": "INA000019406",
        "contact_person": "N Prabhanjan Rao",
            "Address": "7, Sridevi Complex, NAT Street, Basavanagudi",
            "City": "BANGALORE",
            "State": "KARNATAKA",
            "pincode": "560004",
        "Email": "rao@cfooptimus.com",
        "Telephone": "917760796280",
        "fax": null,
        "registration_date": "Jul 18, 2024",
        "license_type": "Perpetual",
        "category": "MFD",
        "Book Slot":"Book"
    }
]
